### ISSUE TITLE
Ship trading & builtby

### ISSUE THREAD

**Issue by Demolish50** [jpcsupplies/Economy_mod#169]
Ship trading needs to also change the builtby attribute. If you don't, when someone removes their owned block it removed all the blocks on the ship that was traded.

**Comment by TheEngineer50** [comment]
Every block you build, even armor blocks have a builtby node that contains the playerid of the player who built it. It's how the in game block limit system keeps track of who built what blocks.

**Comment by TheEngineer50** [comment]
let me find an example

**Comment by midspace** [comment]
Agreed. Not changing the BuiltBy is dangerous.

Sample code for changing it is located here.
https://github.com/midspace/Space-Engineers-Admin-script-mod/blob/master/midspace%20admin%20helper/Data/Scripts/midspace.adminscripts/Messages/Sync/MessageSyncGridChange.cs#L242

**Comment by jpcsupplies** [comment]
also not sure if related just had a crash after using sell ship buyship and bal: 
2017-03-26 16:17:21.123 - Thread:   1 ->  Exception occured: System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.KeyCollection.Enumerator.MoveNext()
   at Sandbox.Game.Entities.Cube.MyCubeGridOwnershipManager.RecalculateOwners()
   at Sandbox.Game.Entities.MyCubeGrid.DoLazyUpdates()
   at Sandbox.Game.Entities.MyCubeGrid.UpdateAfterSimulation()
   at Sandbox.Game.Entities.MyEntities.<UpdateAfterSimulation>b__d(MyEntity x)
   at VRage.Collections.MyDistributedUpdater`2.Iterate(Action`1 p)
   at Sandbox.Game.Entities.MyEntities.UpdateAfterSimulation()
   at Sandbox.Game.World.MySector.UpdateAfterSimulation()
   at Sandbox.Game.World.MySession.UpdateComponents()
   at Sandbox.Game.World.MySession.Update(MyTimeSpan updateTime)
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass1.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at VRage.Dedicated.DedicatedServer.RunInternal()
   at VRage.Dedicated.DedicatedServer.RunMain(String instanceName, String customPath, Boolean isService, Boolean showConsole)
   at VRage.Dedicated.DedicatedServer.ProcessArgs(String[] args)
   at VRage.Dedicated.DedicatedServer.Run[T](String[] args)
   at SpaceEngineersDedicated.MyProgram.Main(String[] args)
2017-03-26 16:17:21.127 - Thread:   1 ->  Hiding window

**Comment by jpcsupplies** [comment]
So looks like we need to change https://github.com/jpcsupplies/Economy_mod/blob/master/Economy/Data/Scripts/Economy.scripts/Messages/MessageShipSale.cs#L248  to also do ` ((MyCubeGrid)grid).TransferBlocksBuiltByID(identity.IdentityId, selectedPlayer.IdentityId);`

Since non owned blocks also have a built by, we also need to rework the code that skips over armor blocks etc, and change that too..   ?

**Comment by midspace** [comment]
Can some explain to me what the loop starting here does?
https://github.com/jpcsupplies/Economy_mod/blob/master/Economy/Data/Scripts/Economy.scripts/Messages/MessageShipSale.cs#L254

Because as far as I understand, ownership was changed at L250.
There are lots of calls to fetch the block definition using GetObjectBuilder(), which is a very costly operation, and then nothing uses the definition.

@temar96

**Comment by temar96** [comment]
your right i dont see a purpose in those 2 lines, it may have been used for something earlier on in the coding

**Comment by temar96** [comment]
the loop changes ownership of the individual blocks that have ownership but the blockDefintion variable doesnt seem to be used

**Comment by jpcsupplies** [comment]
So far testers seem to indicate other than a brief client residue which goes away when they reconnect the issue seems to resolved by your last commit.

**Comment by midspace** [comment]
Could you elaborate on what `client residue` is?

**Comment by jpcsupplies** [comment]
when ownership changes,    the local client still see's it as not changed.. so its like "residual" traces of the prior ownership.    If they reconnect both client and server see the new owner fine.

**Comment by jpcsupplies** [comment]
AFAIK this is now all working correctly
