### ISSUE TITLE
Torch (aka SESE reboot) compatability issue message queue

### ISSUE THREAD

**Issue by jpcsupplies** [jpcsupplies/Economy_mod#194]
Torch seems to be throwing a reference instance error on economy.  Suspect outdated version of Torch.   

2019-06-07 20:53:06.193 - System.NullReferenceException: Object reference not set to an instance of an object.
at Economy.scripts.EconomyScript.ProcessMessage(String messageText)
at Economy.scripts.EconomyScript.GotMessage(String messageText, Boolean& sendToOthers)

2019-06-07 20:53:10.465 - Delayed Connection Request

**Comment by jpcsupplies** [comment]
ModApi utilities seems to be throwing warnings on message handler, this seems consistent with the intiial RegisterMessageHandler warning,    may be a case of another renamed or obsolete object name to chase up,   visual studio shows 19 warnings in this regard
