### ISSUE TITLE
BUG: sell command causes CTD on single quote

### ISSUE THREAD

**Issue by jpcsupplies** [jpcsupplies/Economy_mod#50]
/sell 1 i"ron ingot 
results in following crash:

2015-10-04 09:10:07.615 - Thread:   1 ->  Exception occured: System.NullReferenceException: Object reference not set to an instance of an object.
   at Economy.scripts.EconomyScript.ProcessMessage(String messageText)
   at Economy.scripts.EconomyScript.GotMessage(String messageText, Boolean& sendToOthers)
   at Sandbox.Game.Gui.MyGuiScreenChat.HandleInput(Boolean receivedFocusInThisUpdate)
   at Sandbox.Graphics.GUI.MyScreenManager.HandleInput()
   at Sandbox.Graphics.GUI.MyDX9Gui.HandleInput()
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.FixedRenderLoop.<>c__DisplayClass2.<Run>b__1()
   at Sandbox.Engine.Platform.GenericRenderLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.FixedRenderLoop.Run(VoidAction tickCallback)
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at SpaceEngineers.MyProgram.RunInternal(String[] args)
   at SpaceEngineers.MyProgram.Main(String[] args)

**Comment by midspace** [comment]
I merged some logic which cancelled out a conditional check.
Am fixing now.
