### ISSUE TITLE
BUG Unknown - single player - appears to be to message handling

### ISSUE THREAD

**Issue by jpcsupplies** [jpcsupplies/Economy_mod#68]
This was reported on the main steam page for the mod -
Sounds like a fresh install. I've asked for more information. (he used command /buy 1 ingot uranium)
So he wasnt inputting correct buy/sell order but still shouldnt throw an error like that.
Hopefully it is something we already fixed on the github version.

[quote]
[KOR]dldmltls1 19 minutes ago  
i test this mod on my single world

i can buy&sell other item.

but can't trade ore&ingot and take this error

2015-10-11 15:02:35:342 Error - System.ArgumentOutOfRangeException: startIndex cannot be larger than length of string.
Parameter name: startIndex
at System.String.Substring(Int32 startIndex, Int32 length)
at Economy.scripts.Support.FindPhysicalParts(String itemName, MyObjectBuilder_Base& objectBuilder, String[]& options)
at Economy.scripts.EconomyScript.ProcessMessage(String messageText)
at Economy.scripts.EconomyScript.GotMessage(String messageText, Boolean& sendToOthers)

i this is bug?
[/quote]

**Comment by jpcsupplies** [comment]
current does throw exception but our catcher stops it being fatal
